# Generated by Django 5.1.3 on 2025-04-06 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_project', '0002_expense_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='type',
            field=models.CharField(choices=[('Expense', 'Expense'), ('Income', 'Income')], default='Expense', max_length=10),
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('Business Expenses', 'Business Expenses'), ('Debt', 'Debt'), ('Education', 'Education'), ('Entertainment', 'Entertainment'), ('Food', 'Food'), ('Gifts', 'Gifts'), ('Health', 'Health'), ('Home Maintenance', 'Home Maintenance'), ('Housing', 'Housing'), ('Insurance', 'Insurance'), ('Others', 'Others'), ('Personal Care', 'Personal Care'), ('Pets', 'Pets'), ('Savings', 'Savings'), ('Shopping', 'Shopping'), ('Subscriptions', 'Subscriptions'), ('Taxes', 'Taxes'), ('Transport', 'Transport'), ('Travel', 'Travel'), ('Utilities', 'Utilities')], default='Others', max_length=50),
        ),
    ]
