# Generated by Django 5.1.3 on 2025-04-19 16:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_project', '0003_expense_type_alter_expense_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Business Expenses', 'Business Expenses'), ('Debt', 'Debt'), ('Education', 'Education'), ('Entertainment', 'Entertainment'), ('Food', 'Food'), ('Gifts', 'Gifts'), ('Health', 'Health'), ('Home Maintenance', 'Home Maintenance'), ('Housing', 'Housing'), ('Insurance', 'Insurance'), ('Others', 'Others'), ('Personal Care', 'Personal Care'), ('Pets', 'Pets'), ('Savings', 'Savings'), ('Shopping', 'Shopping'), ('Subscriptions', 'Subscriptions'), ('Taxes', 'Taxes'), ('Transport', 'Transport'), ('Travel', 'Travel'), ('Utilities', 'Utilities')], max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
