# Generated by Django 5.1.3 on 2025-04-19 16:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_project', '0005_rename_amount_budget_limit_remove_budget_month_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='month',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
