# Generated by Django 5.1.3 on 2025-04-23 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_project', '0006_budget_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='year',
            field=models.IntegerField(default=2025),
        ),
        migrations.AlterField(
            model_name='budget',
            name='month',
            field=models.IntegerField(),
        ),
    ]
