# Generated by Django 5.1.3 on 2025-04-23 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_project', '0007_budget_year_alter_budget_month'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budget',
            name='month',
        ),
        migrations.RemoveField(
            model_name='budget',
            name='year',
        ),
    ]
